[server]
  log_path = "./logs/server.log"

[redis]
  addr = ":6379"

[market]
  intervals = ["5m", "15m", "30m", "1h", "4h", "1d"]

[chart]
  [chart.candles]
    limit = 1000

[binance]
  [binance.rate_limit]
    requests = 800
    duration = "1m"
  [binance.config]
    production = false
    api_key = "tshhh50wl5HeGOkDXuA4soO81AWyX3AztDb9KoedzZuQ1CSpVidXllJAJzPhXGUB"
    secret_key = "KGzctvmH5tsAm4GMTKxbVMwPFybnqIgWBH2rtVgalwyJpM1H2Qax7hyvnYH5i8hy"

[telegram]
  trading_bot_token = "5629721774:AAH0Uq1xuqw7oKPSVQrNIDjeT8EgZgMuMZg"

[notify_channels]
  futures_recommendation = -653827904
  orders_creation = 1630847448

[notify_worker]
  size = 64

[trader]
  size = 2