[server]
  log_path = "./tmp/server.log"

[redis]
  addr = ":6379"

[market]
  intervals = ["5m", "15m", "30m", "1h", "4h", "1d"]

[chart]
  [chart.candles]
    limit = 1000

[binance]
  [binance.rate_limit]
    requests = 800
    duration = "1m"
  [binance.config]
    production = false
    api_key = "24a91b0057cd5df6f3fa4c9e059511670d84951b8b1e4cb3eb725b75b7a855bc"
    secret_key = "c6fcd23215be8e792ce8262e5f2c180abdb4aa9ec832d1c54bacad90e0437ae7"

[telegram]
  trading_bot_token = "5392735903:AAHgMUpDqcKyiSbYLgVfZkKaOLjYPsLkgBs"

[notify_channels]
  futures_recommendation = 1630847448
  orders_creation = 1630847448

[notify_worker]
  size = 64

[trader]
  size = 2