[server]
  log_path = "./logs/server.log"
  env = "prod"

[redis]
  addr = ":6379"

[market]
  intervals = ["5m", "15m", "30m", "1h", "4h", "1d"]

[chart]
  [chart.candles]
    limit = 1000

[binance]
  [binance.rate_limit]
    requests = 200
    duration = "1m"
  [binance.config]
    [binance.config.futures] # read and write
      order_url = "https://testnet.binancefuture.com" # testnet
      feed_url = "https://fapi.binance.com" # real
      api_key = "24a91b0057cd5df6f3fa4c9e059511670d84951b8b1e4cb3eb725b75b7a855bc" # testnet
      secret_key = "c6fcd23215be8e792ce8262e5f2c180abdb4aa9ec832d1c54bacad90e0437ae7" # testnet

    [binance.config.production] # read only
      api_key = "S1adYzFTy1Xoa8VAN98rT6R5QCYGTZYkfdMCzI3gcyU5yxuTPYxmpqC0ompwVLP3"
      secret_key = "9FRWjhJErghBU7BhbO412RV6WwU9ErEsWy7e0Idf6V5OEu3PTH3zvNicZ3SW2ZV3"

[telegram]
  trading_bot_token = "5629721774:AAH0Uq1xuqw7oKPSVQrNIDjeT8EgZgMuMZg"

[notify]
  [notify.channels]
    futures_recommendation = -653827904
    orders_creation = -1001795149770
  [notify.worker]
    size = 64
  [notify.config]
    expiration = "10m"

[trader]
  size = 2