services:
  redis:
    container_name: redis-server
    image: redis:6.2.7-alpine
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "5s"
      retries: 3
      timeout: "30s"
    ports: 
      - "6380:6379"
    networks:
      - back-tier
    restart: always

  analyzer:
    container_name: analyzer
    build:
      context: .
      dockerfile: ./internal/servers/analyzer/Dockerfile
    image: analyzer:latest
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
      - "./logs:/logs"
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - back-tier
    restart: always

  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: ./internal/servers/crawler/Dockerfile
    image: crawler:latest
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
      - "./logs:/logs"
    ports:
      - "5002:8080"
      - "5003:8081"
    networks:
      - back-tier
    restart: always

  notifier:
    container_name: notifier
    build:
      context: .
      dockerfile: ./internal/servers/notifier/Dockerfile
    image: notifier:latest
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
      - "./logs:/logs"
    ports:
      - "5004:8080"
      - "5005:8081"
    networks:
      - back-tier
    restart: always

  trader:
    container_name: trader
    build:
      context: .
      dockerfile: ./internal/servers/trader/Dockerfile
    image: trader:latest
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
      - "./logs:/logs"
    ports:
      - "5006:8080"
      - "5007:8081"
    networks:
      - back-tier
    restart: always

volumes:
  data:

networks:
  back-tier: