[notifier]
  host = ""
  port = 8080
  log_path = "./logs/notifier.log"

[redis]
  addr = ":6379"

[market]
  intervals = ["30m", "1h", "4h", "1d"]

[chart]
  [chart.candles]
    limit = 1000

[binance]
  [binance.rate_limit]
    requests = 200
    duration = "1m"
  [binance.config]
    order_url = "https://testnet.binancefuture.com" # testnet
    feed_url = "https://fapi.binance.com" # real

[telegram]
  # trading_bot_token = "5629721774:AAH0Uq1xuqw7oKPSVQrNIDjeT8EgZgMuMZg"
  trading_bot_token = "5392735903:AAHgMUpDqcKyiSbYLgVfZkKaOLjYPsLkgBs"
