[analyzer]
  log_path = "./logs/analyzer.log"

[notifier]
  addr = "notifier:8080"

[redis]
  addr = "redis:6379"

[market]
  intervals = ["30m", "1h", "4h", "1d"]

[binance]
  [binance.rate_limit]
    requests = 200
    duration = "1m"
  [binance.config]
    order_url = "https://testnet.binancefuture.com" # testnet
    feed_url = "https://fapi.binance.com" # real

[notify]
  [notify.channels]
    futures_recommendation = -653827904
    # futures_recommendation = -1001795149770
    orders_creation = -1001795149770
  [notify.config]
    expiration = "10m"
